/*global systemDictionary:true */
'use strict';

systemDictionary = {
	'APIConnectionSettings': {
		'en': 'API connection settings',
		'de': 'API-Verbindungseinstellungen',
		'ru': 'Настройки подключения API',
		'pt': 'Configurações de conexão API',
		'nl': 'Instellingen voor API-verbinding',
		'fr': 'Paramètres de connexion API',
		'it': 'Impostazioni di connessione API',
		'es': 'Configuración de conexión API',
		'pl': 'Ustawienia połączenia API',
		'zh-cn': 'API 连接设置'
	},
	'location': {
		'en': 'city',
		'de': 'Stadt',
		'ru': 'город',
		'pt': 'cidade',
		'nl': 'stad',
		'fr': 'ville',
		'it': 'città',
		'es': 'ciudad',
		'pl': 'Miasto',
		'zh-cn': '城市'
	},
	'locationHint': {
		'en': 'e.g. Basel',
		'de': 'z.B. Basel',
		'ru': 'например Базель',
		'pt': 'por exemplo. Basel',
		'nl': 'bijv. Bazel',
		'fr': 'par exemple. Bâle',
		'it': 'per esempio. Basilea',
		'es': 'p.ej. Basilea',
		'pl': 'np. Bazylea',
		'zh-cn': '例如巴塞尔'
	},
	'locationFromSystem':  {
		'en': 'Adopt city from system',
		'de': 'Stadt aus System übernehmen',
		'ru': 'Заимствовать город из системы',
		'pt': 'Adote a cidade do sistema',
		'nl': 'Stad uit systeem overnemen',
		'fr': 'Adopter la ville du système',
		'it': 'Adotta la città dal sistema',
		'es': 'Adopte la ciudad del sistema',
		'pl': 'Zaadoptuj miasto z systemu',
		'zh-cn': '从系统采用城市'
	},
	'latitude': {
		'en': 'latitude WGS84',
		'de': 'Breitengrad WGS84',
		'ru': 'широта WGS84',
		'pt': 'latitude WGS84',
		'nl': 'latitude WGS84',
		'fr': 'latitude WGS84',
		'it': 'latitude WGS84',
		'es': 'latitud WGS84',
		'pl': 'latitude WGS84',
		'zh-cn': 'latitude WGS84'
	},
	'latitudeHint': {
		'en': 'e.g. 47.55814',
		'de': 'z.B. 47.55814',
		'ru': 'например 47,55814',
		'pt': 'por exemplo. 47.55814',
		'nl': 'bijv. 47.55814',
		'fr': 'par exemple. 47.55814',
		'it': 'per esempio. 47.55814',
		'es': 'p.ej. 47.55814',
		'pl': 'np. 47,55814',
		'zh-cn': '例如47.55814'
	},
	'longitude': {
		'en': 'longitude WGS84',
		'de': 'Längengrad WGS84',
		'ru': 'долгота WGS84',
		'pt': 'longitude WGS84',
		'nl': 'lengtegraad WGS84',
		'fr': 'longitude WGS84',
		'it': 'longitudine WGS84',
		'es': 'longitud WGS84',
		'pl': 'długość geograficzna WGS84',
		'zh-cn': '经度 WGS84'
	},
	'longitudeHint': {
		'en': 'e.g. 7.58769',
		'de': 'z.B. 7.58769',
		'ru': 'например 7,58769',
		'pt': 'por exemplo. 7,58769',
		'nl': 'bijv. 7.58769',
		'fr': 'par exemple. 7.58769',
		'it': 'per esempio. 7.58769',
		'es': 'p.ej. 7.58769',
		'pl': 'np. 7,58769',
		'zh-cn': '例如7.58769'
	},
	'latlongFromSystem': {
		'en': 'Adopt latitide and longitude from system',
		'de': 'Breiten- und Längengrad vom System übernehmen',
		'ru': 'Принять широту и долготу из системы',
		'pt': 'Adote latitude e longitude do sistema',
		'nl': 'Adopteer breedte- en lengtegraad uit het systeem',
		'fr': 'Adopter la latitude et la longitude du système',
		'it': 'Adotta latitide e longitudine dal sistema',
		'es': 'Adopte la latitud y la longitud del sistema',
		'pl': 'Przejmij szerokość i długość geograficzną z systemu',
		'zh-cn': '从系统中采用纬度和经度'
	},
	'elevation':  {
		'en': 'elevation (meters above sea)',
		'de': 'Höhe (Meter über Meer)',
		'ru': 'высота (метры над уровнем моря)',
		'pt': 'elevação (metros acima do mar)',
		'nl': 'hoogte (meters boven zee)',
		'fr': 'altitude (mètres au-dessus de la mer)',
		'it': 'elevazione (metri sopra il mare)',
		'es': 'elevación (metros sobre el mar)',
		'pl': 'wysokość (m nad poziomem morza)',
		'zh-cn': '海拔（海拔米）'
	},
	'elevationHint': {
		'en': 'e.g. 260',
		'de': 'z.B. 260',
		'ru': 'например 260',
		'pt': 'por exemplo. 260',
		'nl': 'bijv. 260',
		'fr': 'par exemple. 260',
		'it': 'per esempio. 260',
		'es': 'p.ej. 260',
		'pl': 'np. 260',
		'zh-cn': '例如260'
	},
	'timezone': {
		'en': 'timezone',
		'de': 'Zeitzone',
		'ru': 'часовой пояс',
		'pt': 'fuso horário',
		'nl': 'tijdzone',
		'fr': 'fuseau horaire',
		'it': 'fuso orario',
		'es': 'zona horaria',
		'pl': 'strefa czasowa',
		'zh-cn': '时区'
	},
	'temperature': {
		'en': 'Teperature unit',
		'de': 'Temperatureinheit',
		'ru': 'Единица измерения температуры',
		'pt': 'Unidade de temperatura',
		'nl': 'temperatuur eenheid',
		'fr': 'Unité de température',
		'it': 'Unità di temperatura',
		'es': 'Unidad de temperatura',
		'pl': 'Jednostka temperatury',
		'zh-cn': '温度单位'
	},
	'celsius': {
		'en': 'celsius',
		'de': 'Celsius',
		'ru': 'по Цельсию',
		'pt': 'Celsius',
		'nl': 'Celsius',
		'fr': 'celsius',
		'it': 'centigrado',
		'es': 'Celsius',
		'pl': 'Celsjusz',
		'zh-cn': '摄氏'
	},
	'farenheit': {
		'en': 'farenheit',
		'de': 'Fahrenheit',
		'ru': 'Фаренгейт',
		'pt': 'farenheit',
		'nl': 'farenheit',
		'fr': 'farenheit',
		'it': 'farenheit',
		'es': 'farenheit',
		'pl': 'Farenheita',
		'zh-cn': '华氏度'
	},
	'tempunitFromSystem': {
		'en': 'Adopt temperature unit from system',
		'de': 'Temperatureinheit vom System übernehmen',
		'ru': 'Принять единицу измерения температуры из системы',
		'pt': 'Adote a unidade de temperatura do sistema',
		'nl': 'Adopteer temperatuureenheid van systeem:',
		'fr': 'Adopter l\'unité de température du système',
		'it': 'Adotta l\'unità di temperatura dal sistema',
		'es': 'Adopte la unidad de temperatura del sistema',
		'pl': 'Przejmij jednostkę temperatury z systemu',
		'zh-cn': '采用系统温度单位'
	},
	'windspeed': {
		'en': 'unit of wind speed',
		'de': 'Einheit der Windgeschwindigkeit',
		'ru': 'единица скорости ветра',
		'pt': 'unidade de velocidade do vento',
		'nl': 'eenheid van windsnelheid',
		'fr': 'unité de vitesse du vent',
		'it': 'unità di velocità del vento',
		'es': 'unidad de velocidad del viento',
		'pl': 'jednostka prędkości wiatru',
		'zh-cn': '风速单位'
	},
	'kilometer per hour': {
		'en': 'kilometer per hour',
		'de': 'Kilometer pro Stunde',
		'ru': 'километр в час',
		'pt': 'quilometro por hora',
		'nl': 'kilometer per uur',
		'fr': 'kilomètre par heure',
		'it': 'chilometro all\'ora',
		'es': 'kilómetro por hora',
		'pl': 'kilometr na godzinę',
		'zh-cn': '每小时公里'
	},
	'meter per second': {
		'en': 'meter per second',
		'de': 'Meter pro Sekunde',
		'ru': 'метр в секунду',
		'pt': 'metro por segundo',
		'nl': 'meter per seconde',
		'fr': 'mètre par seconde',
		'it': 'metro al secondo',
		'es': 'metro por segundo',
		'pl': 'metr na sekundę',
		'zh-cn': '米每秒'
	},
	'miles per hour': {
		'en': 'miles per hour',
		'de': 'Meilen pro Stunde',
		'ru': 'миль в час',
		'pt': 'milhas por hora',
		'nl': 'mijl per uur',
		'fr': 'miles par heure',
		'it': 'miglia all\'ora',
		'es': 'millas por hora',
		'pl': 'mile na godzinę',
		'zh-cn': '英里每小时'
	},
	'knots': {
		'en': 'knots',
		'de': 'Knoten',
		'ru': 'узлы',
		'pt': 'nós',
		'nl': 'knopen',
		'fr': 'nœuds',
		'it': 'nodi',
		'es': 'nudos',
		'pl': 'węzły',
		'zh-cn': '结'
	},
	'beaufort': {
		'en': 'beaufort',
		'de': 'beauffort',
		'ru': 'Бофорт',
		'pt': 'Beaufort',
		'nl': 'schoonheid',
		'fr': 'beaufort',
		'it': 'bello',
		'es': 'Beaufort',
		'pl': 'piękna',
		'zh-cn': '博福特'
	},
	'precipitationamount': {
		'en': 'unit of precipitationamount',
		'de': 'Einheit der Niederschlagsmenge',
		'ru': 'единица осадков',
		'pt': 'unidade de quantidade de precipitação',
		'nl': 'eenheid van neerslaghoeveelheid',
		'fr': 'unité de quantité de précipitation',
		'it': 'unità di precipitazione',
		'es': 'unidad de precipitación cantidad',
		'pl': 'jednostka ilości opadu',
		'zh-cn': '降水量单位'
	},
	'mm': {
		'en': 'mm',
		'de': 'mm',
		'ru': 'мм',
		'pt': 'milímetros',
		'nl': 'mm',
		'fr': 'mm',
		'it': 'mm',
		'es': 'mm',
		'pl': 'mm',
		'zh-cn': '毫米'
	},
	'inch': {
		'en': 'inch',
		'de': 'Zoll',
		'ru': 'дюйм',
		'pt': 'polegada',
		'nl': 'inch',
		'fr': 'pouce',
		'it': 'pollice',
		'es': 'pulgada',
		'pl': 'cal',
		'zh-cn': '英寸'
	},
	'apikey': {
		'en': 'API-Key',
		'de': 'API-Schlüssel',
		'ru': 'API-ключ',
		'pt': 'API-Key',
		'nl': 'API-sleutel',
		'fr': 'Clé API',
		'it': 'Chiave API',
		'es': 'API-Key',
		'pl': 'Klucz API',
		'zh-cn': 'API-Key'
	},
	'apikeyHint': {
		'en': 'Get meteoblue non-commercial API service <a href=\'https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\' target=\'_blank\'>here</a>.',
		'de': 'Erhalten Sie den meteoblue nicht-kommerziellen API - Service <a href=\'https://content.meteoblue.com/de/zugangsoptionen/meteoblue-wetter-api/nicht-kommerzielle-nutzung\' target=\'_blank\'>hier</a>.',
		'ru': 'Получите некоммерческий API-сервис meteoblue <a href=\'https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\' target=\'_blank\'>здесь</a>.',
		'pt': 'Obtenha o serviço API não comercial de meteoblue <a href=\'https://content.meteoblue.com/pt/formas-de-acesso/api-meteorologica-de-meteoblue/uso-comercial-nao-comercial\' target=\'_blank\'>aqui</a>.',
		'nl': 'Get meteoblue niet-commercieel API <a href=\'https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\' target=\'_blank\'>hier</a>.',
		'fr': 'Obtenez le service API non commercial de meteoblue <a href=\'https://content.meteoblue.com/fr/modes-d-acces/api-meteo-de-meteoblue/utilisation-non-commercial\' target=\'_blank\'>ici</a>.',
		'it': 'Ottieni il servizio API non commerciale di meteoblue <a href=\'https://content.meteoblue.com/it/forme-di-accesso/api-meteoblue/uso-non-commerciale\' target=\'_blank\'>qui</a>.',
		'es': 'Obtenga el servicio API no comercial de meteoblue <a href=\'https://content.meteoblue.com/es/modos-de-accesso/api-meteorologica-de-meteoblue/uso-no-comercial\' target=\'_blank\'>aquí</a>.',
		'pl': 'Skorzystaj z niekomercyjnej usługi API meteoblue <a href=\'https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\' target=\'_blank\'>tutaj</a>.',
		'zh-cn': '<a href=\'https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\' target=\'_blank\'>在此处</a>获取meteoblue 非商业API 服务。'
	},
	'api_explanation': {
		'en': 'For non-commercial uses, meteoblue.com offers the meteogram 5 days and the data package basic-day. A description of the values can be found <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>here</a>.',
		'de': 'Für nicht-kommerzielle Zwecke bietet meteoblue.com das Meteogramm 5 Tage und das Datenpaket Basic-Day an. Nicht-kommerzielle Nutzungen sind alle Nutzungen ohne unmittelbaren Gewinnzweck. Eine Beschreibung der Werte finden Sie <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>hier</a>.',
		'ru': 'Для некоммерческого использования meteoblue.com предлагает метеограмму за 5 дней и пакет данных «базовый день». Некоммерческое использование - это все виды использования без прямой прибыли. Описание значений можно найти <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>здесь</a>.',
		'pt': 'Para usos não comerciais, meteoblue.com oferece o meteograma 5 dias e o pacote de dados básico-dia. Usos não comerciais são todos os usos sem fins lucrativos diretos. Uma descrição dos valores pode ser encontrada <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>aqui</a>.',
		'nl': 'Voor niet-commercieel gebruik biedt meteoblue.com het meteogram 5 dagen en het datapakket basisdag aan. Niet-commercieel gebruik is elk gebruik zonder directe winstoogmerk. Een beschrijving van de waarden vindt u <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>hier</a>.',
		'fr': 'Pour des usages non commerciaux, meteoblue.com propose le météogramme 5 jours et le forfait data base-jour. Les utilisations non commerciales sont toutes des utilisations sans but lucratif direct. Une description des valeurs peut être trouvée <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>ici</a>.',
		'it': 'Per usi non commerciali, meteoblue.com offre il meteogramma 5 giorni e il pacchetto dati basic-day. Gli usi non commerciali sono tutti gli usi senza fini di lucro diretto. Una descrizione dei valori può essere trovata <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>qui</a>.',
		'es': 'Para usos no comerciales, meteoblue.com ofrece el meteograma 5 días y el paquete de datos basic-day. Los usos no comerciales son todos los usos sin fines de lucro directo. Puede encontrar una descripción de los valores <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>aquí</a>.',
		'pl': 'Do zastosowań niekomercyjnych meteoblue.com oferuje meteogram 5 dni i pakiet danych basic-day. Zastosowania niekomercyjne to wszystkie zastosowania bez bezpośredniego zysku. Opis wartości można znaleźć <a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>tutaj</a>.',
		'zh-cn': '对于非商业用途，meteoblue.com 提供 5 天的气象图和基本天的数据包。非商业用途是所有没有直接盈利目的的用途。<a href=\'https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\' target=\'_blank\'>可以在此处</a>找到这些值的说明。'
	},
	'on save adapter restarts with new config immediately': {
		'en': 'on save adapter restarts with new config immediately',
		'de': 'Beim Speichern der Einstellungen wird der Adapter sofort neu gestartet.',
		'ru': 'сохранить адаптера перезагрузки с новый конфиг сразу',
		'pt': 'em salvar adaptador reinicia com nova configuração e imediatamente',
		'nl': 'op bespaar adapter opnieuw met nieuwe config onmiddellijk',
		'fr': 'sur enregistrer l\'adaptateur redémarre avec la nouvelle configuration, immédiatement',
		'it': 'salva adattatore riavvia con la nuova config immediatamente',
		'es': 'en guardar adaptador se reinicia con la nueva config de inmediato',
		'pl': 'zapisz ponownym uruchomieniu zasilacza z nowy konfig raz',
		'zh-cn': '在保存适配器重新启动与新的配置立即'
	}
};
