/*global systemDictionary:true */
'use strict';

systemDictionary = {
		"API connection settings": {
		  "en": "API connection settings",
		  "de": "API-Verbindungseinstellungen",
		  "ru": "Настройки подключения API",
		  "pt": "Configurações de conexão API",
		  "nl": "Instellingen voor API-verbinding",
		  "fr": "Paramètres de connexion API",
		  "it": "Impostazioni di connessione API",
		  "es": "Configuración de conexión API",
		  "pl": "Ustawienia połączenia API",
		  "zh-cn": "API 连接设置"
		},
		"location": {
		  "en": "location",
		  "de": "Lage",
		  "ru": "место нахождения",
		  "pt": "localização",
		  "nl": "plaats",
		  "fr": "emplacement",
		  "it": "Posizione",
		  "es": "localización",
		  "pl": "Lokalizacja",
		  "zh-cn": "地点"
		},
		"latitude": {
		  "en": "latitude",
		  "de": "Breite",
		  "ru": "широта",
		  "pt": "latitude",
		  "nl": "breedtegraad",
		  "fr": "latitude",
		  "it": "latitudine",
		  "es": "latitud",
		  "pl": "szerokość",
		  "zh-cn": "纬度"
		},
		"longitude": {
		  "en": "longitude",
		  "de": "Längengrad",
		  "ru": "долгота",
		  "pt": "longitude",
		  "nl": "Lengtegraad",
		  "fr": "longitude",
		  "it": "longitudine",
		  "es": "longitud",
		  "pl": "długość geograficzna",
		  "zh-cn": "经度"
		},
		"elevation": {
		  "en": "elevation",
		  "de": "Elevation",
		  "ru": "высота",
		  "pt": "elevação",
		  "nl": "verhoging",
		  "fr": "élévation",
		  "it": "elevazione",
		  "es": "elevación",
		  "pl": "podniesienie",
		  "zh-cn": "海拔"
		},
		"timezone": {
		  "en": "timezone",
		  "de": "Zeitzone",
		  "ru": "часовой пояс",
		  "pt": "fuso horário",
		  "nl": "tijdzone",
		  "fr": "fuseau horaire",
		  "it": "fuso orario",
		  "es": "zona horaria",
		  "pl": "strefa czasowa",
		  "zh-cn": "时区"
		},
		"Europe/Zurich": {
		  "en": "Europe/Zurich",
		  "de": "Europa/Zürich",
		  "ru": "Европа/Цюрих",
		  "pt": "Europa/Zurique",
		  "nl": "Europa/Zürich",
		  "fr": "Europe/Zurich",
		  "it": "Europa/Zurigo",
		  "es": "Europa/Zúrich",
		  "pl": "Europa/Zurych",
		  "zh-cn": "欧洲/苏黎世"
		},
		"Europe/Berlin": {
		  "en": "Europe/Berlin",
		  "de": "Europa/Berlin",
		  "ru": "Европа/Берлин",
		  "pt": "Europa/Berlim",
		  "nl": "Europa/Berlijn",
		  "fr": "Europe/Berlin",
		  "it": "Europa/Berlino",
		  "es": "Europa/Berlín",
		  "pl": "Europa/Berlin",
		  "zh-cn": "欧洲/柏林"
		},
		"apikey": {
		  "en": "apikey",
		  "de": "API-Schlüssel",
		  "ru": "апики",
		  "pt": "Chave API",
		  "nl": "API sleutel",
		  "fr": "clé API",
		  "it": "apikey",
		  "es": "Clave API",
		  "pl": "Klucz API",
		  "zh-cn": "apikey"
		},
		"temperature": {
		  "en": "temperature",
		  "de": "Temperatur",
		  "ru": "температура",
		  "pt": "temperatura",
		  "nl": "temperatuur-",
		  "fr": "Température",
		  "it": "temperatura",
		  "es": "temperatura",
		  "pl": "temperatura",
		  "zh-cn": "温度"
		},
		"celsius": {
		  "en": "celsius",
		  "de": "Celsius",
		  "ru": "по Цельсию",
		  "pt": "Celsius",
		  "nl": "Celsius",
		  "fr": "celsius",
		  "it": "centigrado",
		  "es": "Celsius",
		  "pl": "Celsjusz",
		  "zh-cn": "摄氏"
		},
		"farenheit": {
		  "en": "farenheit",
		  "de": "Fahrenheit",
		  "ru": "Фаренгейт",
		  "pt": "farenheit",
		  "nl": "farenheit",
		  "fr": "farenheit",
		  "it": "farenheit",
		  "es": "farenheit",
		  "pl": "Farenheita",
		  "zh-cn": "华氏度"
		},
		"windspeed": {
		  "en": "windspeed",
		  "de": "Windgeschwindigkeit",
		  "ru": "скорость ветра",
		  "pt": "velocidade do vento",
		  "nl": "windsnelheid",
		  "fr": "vitesse du vent",
		  "it": "velocità del vento",
		  "es": "velocidad del viento",
		  "pl": "prędkość wiatru",
		  "zh-cn": "风速"
		},
		"kilometer per hour": {
		  "en": "kilometer per hour",
		  "de": "Kilometer pro Stunde",
		  "ru": "километр в час",
		  "pt": "quilometro por hora",
		  "nl": "kilometer per uur",
		  "fr": "kilomètre par heure",
		  "it": "chilometro all'ora",
		  "es": "kilómetro por hora",
		  "pl": "kilometr na godzinę",
		  "zh-cn": "每小时公里"
		},
		"meter per second": {
		  "en": "meter per second",
		  "de": "Meter pro Sekunde",
		  "ru": "метр в секунду",
		  "pt": "metro por segundo",
		  "nl": "meter per seconde",
		  "fr": "mètre par seconde",
		  "it": "metro al secondo",
		  "es": "metro por segundo",
		  "pl": "metr na sekundę",
		  "zh-cn": "米每秒"
		},
		"miles per hour": {
		  "en": "miles per hour",
		  "de": "Meilen pro Stunde",
		  "ru": "миль в час",
		  "pt": "milhas por hora",
		  "nl": "mijl per uur",
		  "fr": "miles par heure",
		  "it": "miglia all'ora",
		  "es": "millas por hora",
		  "pl": "mile na godzinę",
		  "zh-cn": "英里每小时"
		},
		"knots": {
		  "en": "knots",
		  "de": "Knoten",
		  "ru": "узлы",
		  "pt": "nós",
		  "nl": "knopen",
		  "fr": "nœuds",
		  "it": "nodi",
		  "es": "nudos",
		  "pl": "węzły",
		  "zh-cn": "结"
		},
		"beaufort": {
		  "en": "beaufort",
		  "de": "beauffort",
		  "ru": "Бофорт",
		  "pt": "Beaufort",
		  "nl": "schoonheid",
		  "fr": "beaufort",
		  "it": "bello",
		  "es": "Beaufort",
		  "pl": "piękna",
		  "zh-cn": "博福特"
		},
		"winddirection": {
		  "en": "winddirection",
		  "de": "Windrichtung",
		  "ru": "направление ветра",
		  "pt": "Direção do vento",
		  "nl": "windrichting",
		  "fr": "direction du vent",
		  "it": "la direzione del vento",
		  "es": "dirección del viento",
		  "pl": "kierunek wiatru",
		  "zh-cn": "风向"
		},
		"degree": {
		  "en": "degree",
		  "de": "Grad",
		  "ru": "степень",
		  "pt": "grau",
		  "nl": "rang",
		  "fr": "degré",
		  "it": "livello",
		  "es": "la licenciatura",
		  "pl": "stopień",
		  "zh-cn": "程度"
		},
		"2 direction characters": {
		  "en": "2 direction characters",
		  "de": "2 Richtungszeichen",
		  "ru": "2 символа направления",
		  "pt": "2 caracteres de direção",
		  "nl": "2 richting karakters",
		  "fr": "2 personnages de direction",
		  "it": "2 caratteri di direzione",
		  "es": "2 caracteres de dirección",
		  "pl": "2 znaki kierunkowe",
		  "zh-cn": "2个方向字符"
		},
		"3 direction characters": {
		  "en": "3 direction characters",
		  "de": "3 Richtungszeichen",
		  "ru": "3 символа направления",
		  "pt": "3 caracteres de direção",
		  "nl": "3 richting karakters",
		  "fr": "3 personnages de direction",
		  "it": "3 caratteri di direzione",
		  "es": "3 caracteres de dirección",
		  "pl": "3 znaki kierunkowe",
		  "zh-cn": "3个方向字符"
		},
		"precipitationamount": {
		  "en": "precipitationamount",
		  "de": "Niederschlagsmenge",
		  "ru": "количество осадков",
		  "pt": "quantidade de precipitação",
		  "nl": "neerslaghoeveelheid",
		  "fr": "quantité de précipitations",
		  "it": "quantità di precipitazioni",
		  "es": "cantidad de precipitación",
		  "pl": "ilość opadów",
		  "zh-cn": "降水量"
		},
		"mm": {
		  "en": "mm",
		  "de": "mm",
		  "ru": "мм",
		  "pt": "milímetros",
		  "nl": "mm",
		  "fr": "mm",
		  "it": "mm",
		  "es": "mm",
		  "pl": "mm",
		  "zh-cn": "毫米"
		},
		"inch": {
		  "en": "inch",
		  "de": "Zoll",
		  "ru": "дюйм",
		  "pt": "polegada",
		  "nl": "inch",
		  "fr": "pouce",
		  "it": "pollice",
		  "es": "pulgada",
		  "pl": "cal",
		  "zh-cn": "英寸"
		},
		"timeformat": {
		  "en": "timeformat",
		  "de": "Zeitformat",
		  "ru": "формат времени",
		  "pt": "formato de tempo",
		  "nl": "Tijd formaat",
		  "fr": "format de l'heure",
		  "it": "formato orario",
		  "es": "formato de tiempo",
		  "pl": "format czasu",
		  "zh-cn": "时间格式"
		},
		"Y-M-D": {
		  "en": "Y-M-D",
		  "de": "Y-M-D",
		  "ru": "Г-М-Д",
		  "pt": "Y-M-D",
		  "nl": "J-M-D",
		  "fr": "A-M-D",
		  "it": "Y-M-D",
		  "es": "Y-M-D",
		  "pl": "Y-M-D",
		  "zh-cn": "年-月-日"
		},
		"YMD": {
		  "en": "YMD",
		  "de": "YMD",
		  "ru": "YMD",
		  "pt": "YMD",
		  "nl": "YMD",
		  "fr": "AMJ",
		  "it": "YMD",
		  "es": "YMD",
		  "pl": "YMD",
		  "zh-cn": "长城"
		},
		"iso8601": {
		  "en": "iso8601",
		  "de": "iso8601",
		  "ru": "iso8601",
		  "pt": "iso8601",
		  "nl": "iso8601",
		  "fr": "iso8601",
		  "it": "iso8601",
		  "es": "iso8601",
		  "pl": "iso8601",
		  "zh-cn": "iso8601"
		},
		"timestamp_utc": {
			"en": "timestamp (UTC)",
			"de": "Zeitstempel (UTC)",
			"ru": "отметка времени (UTC)",
			"pt": "carimbo de data / hora (UTC)",
			"nl": "tijdstempel (UTC)",
			"fr": "horodatage (UTC)",
			"it": "timestamp (UTC)",
			"es": "marca de tiempo (UTC)",
			"pl": "znacznik czasu (UTC)",
			"zh-cn": "时间戳 (UTC)"
		},
		"timestamp_ms_utc": {
			"en": "timestamp (MS_UTC)",
			"de": "Zeitstempel (MS_UTC)",
			"ru": "отметка времени (MS_UTC)",
			"pt": "carimbo de data / hora (MS_UTC)",
			"nl": "tijdstempel (MS_UTC)",
			"fr": "horodatage (MS_UTC)",
			"it": "timestamp (MS_UTC)",
			"es": "marca de tiempo (MS_UTC)",
			"pl": "sygnatura czasowa (MS_UTC)",
			"zh-cn": "时间戳 (MS_UTC)"
		},
		"api_explanation": {
			"en": "more information can be found <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">here</a>",
			"de": "weitere Informationen finden Sie <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">hier</a>",
			"ru": "дополнительную информацию можно найти <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">здесь</a>",
			"pt": "mais informações podem ser encontradas <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">aqui</a>",
			"nl": "meer informatie vind je <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">hier</a>",
			"fr": "plus d'informations peuvent être trouvées <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">ici</a>",
			"it": "maggiori informazioni possono essere trovate <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">qui</a>",
			"es": "se puede encontrar más información <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">aquí</a>",
			"pl": "więcej informacji znajdziesz <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">tutaj</a>",
			"zh-cn": "更多信息可以在<a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">这里找到</a>"
		}, 
		"required": {
			"en": "required",
			"de": "erforderlich",
			"ru": "требуется",
			"pt": "obrigatório",
			"nl": "verplicht",
			"fr": "obligatoire",
			"it": "necessario",
			"es": "requerido",
			"pl": "wymagany",
			"zh-cn": "必需的"
		  }
};