/*global systemDictionary:true */
'use strict';

systemDictionary = {
		"API connection settings": {
		  "en": "API connection settings",
		  "de": "API-Verbindungseinstellungen",
		  "ru": "Настройки подключения API",
		  "pt": "Configurações de conexão API",
		  "nl": "Instellingen voor API-verbinding",
		  "fr": "Paramètres de connexion API",
		  "it": "Impostazioni di connessione API",
		  "es": "Configuración de conexión API",
		  "pl": "Ustawienia połączenia API",
		  "zh-cn": "API 连接设置"
		},
		"location": {
		  "en": "location",
		  "de": "Lage",
		  "ru": "место нахождения",
		  "pt": "localização",
		  "nl": "plaats",
		  "fr": "emplacement",
		  "it": "Posizione",
		  "es": "localización",
		  "pl": "Lokalizacja",
		  "zh-cn": "地点"
		},
		"latitude": {
			"en": "latitude WGS84 (default: system configuration)",
			"de": "Breitengrad WGS84 (Standard: Systemkonfiguration)",
			"ru": "широта WGS84 (по умолчанию: конфигурация системы)",
			"pt": "latitude WGS84 (padrão: configuração do sistema)",
			"nl": "latitude WGS84 (standaard: systeemconfiguratie)",
			"fr": "latitude WGS84 (par défaut : configuration du système)",
			"it": "latitude WGS84 (predefinito: configurazione del sistema)",
			"es": "latitud WGS84 (predeterminado: configuración del sistema)",
			"pl": "latitude WGS84 (domyślnie: konfiguracja systemu)",
			"zh-cn": "latitude WGS84（默认：系统配置）"
		},
		"longitude": {
			"en": "longitude WGS84 (default: system configuration)",
			"de": "Längengrad WGS84 (Standard: Systemkonfiguration)",
			"ru": "долгота WGS84 (по умолчанию: конфигурация системы)",
			"pt": "longitude WGS84 (padrão: configuração do sistema)",
			"nl": "lengtegraad WGS84 (standaard: systeemconfiguratie)",
			"fr": "longitude WGS84 (par défaut : configuration du système)",
			"it": "longitudine WGS84 (predefinito: configurazione del sistema)",
			"es": "longitud WGS84 (predeterminado: configuración del sistema)",
			"pl": "długość geograficzna WGS84 (domyślnie: konfiguracja systemu)",
			"zh-cn": "经度 WGS84（默认：系统配置）"
		},
		"elevation": {
			"en": "elevation (default: automatic detection)",
			"de": "Höhe (Standard: automatische Erkennung)",
			"ru": "высота (по умолчанию: автоматическое определение)",
			"pt": "elevação (padrão: detecção automática)",
			"nl": "hoogte (standaard: automatische detectie)",
			"fr": "altitude (par défaut : détection automatique)",
			"it": "elevazione (impostazione predefinita: rilevamento automatico)",
			"es": "elevación (predeterminado: detección automática)",
			"pl": "elewacja (domyślnie: automatyczne wykrywanie)",
			"zh-cn": "海拔（默认：自动检测）"
		},
		"timezone": {
			"en": "timezone (default: automatic detection)",
			"de": "Zeitzone (Standard: automatische Erkennung)",
			"ru": "часовой пояс (по умолчанию: автоматическое определение)",
			"pt": "fuso horário (padrão: detecção automática)",
			"nl": "tijdzone (standaard: automatische detectie)",
			"fr": "fuseau horaire (par défaut : détection automatique)",
			"it": "fuso orario (predefinito: rilevamento automatico)",
			"es": "zona horaria (predeterminado: detección automática)",
			"pl": "strefa czasowa (domyślnie: automatyczne wykrywanie)",
			"zh-cn": "时区（默认：自动检测）"
		},
		"apikey": {
			"en": "API-Key (required)",
			"de": "API-Schlüssel (erforderlich)",
			"ru": "API-ключ (обязательно)",
			"pt": "API-Key (obrigatório)",
			"nl": "API-sleutel (verplicht)",
			"fr": "Clé API (obligatoire)",
			"it": "Chiave API (richiesto)",
			"es": "API-Key (requerido)",
			"pl": "Klucz API (wymagany)",
			"zh-cn": "API-Key（必填）"
		},
		"temperature": {
			"en": "temperature",
			"de": "Temperatur",
			"ru": "температура",
			"pt": "temperatura",
			"nl": "temperatuur-",
			"fr": "Température",
			"it": "temperatura",
			"es": "temperatura",
			"pl": "temperatura",
			"zh-cn": "温度"
		},
		"celsius": {
		  "en": "celsius",
		  "de": "Celsius",
		  "ru": "по Цельсию",
		  "pt": "Celsius",
		  "nl": "Celsius",
		  "fr": "celsius",
		  "it": "centigrado",
		  "es": "Celsius",
		  "pl": "Celsjusz",
		  "zh-cn": "摄氏"
		},
		"farenheit": {
		  "en": "farenheit",
		  "de": "Fahrenheit",
		  "ru": "Фаренгейт",
		  "pt": "farenheit",
		  "nl": "farenheit",
		  "fr": "farenheit",
		  "it": "farenheit",
		  "es": "farenheit",
		  "pl": "Farenheita",
		  "zh-cn": "华氏度"
		},
		"windspeed": {
			"en": "windspeed",
			"de": "Windgeschwindigkeit",
			"ru": "скорость ветра",
			"pt": "velocidade do vento",
			"nl": "windsnelheid",
			"fr": "vitesse du vent",
			"it": "velocità del vento",
			"es": "velocidad del viento",
			"pl": "prędkość wiatru",
			"zh-cn": "风速"
		},
		"kilometer per hour": {
		  "en": "kilometer per hour",
		  "de": "Kilometer pro Stunde",
		  "ru": "километр в час",
		  "pt": "quilometro por hora",
		  "nl": "kilometer per uur",
		  "fr": "kilomètre par heure",
		  "it": "chilometro all'ora",
		  "es": "kilómetro por hora",
		  "pl": "kilometr na godzinę",
		  "zh-cn": "每小时公里"
		},
		"meter per second": {
		  "en": "meter per second",
		  "de": "Meter pro Sekunde",
		  "ru": "метр в секунду",
		  "pt": "metro por segundo",
		  "nl": "meter per seconde",
		  "fr": "mètre par seconde",
		  "it": "metro al secondo",
		  "es": "metro por segundo",
		  "pl": "metr na sekundę",
		  "zh-cn": "米每秒"
		},
		"miles per hour": {
		  "en": "miles per hour",
		  "de": "Meilen pro Stunde",
		  "ru": "миль в час",
		  "pt": "milhas por hora",
		  "nl": "mijl per uur",
		  "fr": "miles par heure",
		  "it": "miglia all'ora",
		  "es": "millas por hora",
		  "pl": "mile na godzinę",
		  "zh-cn": "英里每小时"
		},
		"knots": {
		  "en": "knots",
		  "de": "Knoten",
		  "ru": "узлы",
		  "pt": "nós",
		  "nl": "knopen",
		  "fr": "nœuds",
		  "it": "nodi",
		  "es": "nudos",
		  "pl": "węzły",
		  "zh-cn": "结"
		},
		"beaufort": {
		  "en": "beaufort",
		  "de": "beauffort",
		  "ru": "Бофорт",
		  "pt": "Beaufort",
		  "nl": "schoonheid",
		  "fr": "beaufort",
		  "it": "bello",
		  "es": "Beaufort",
		  "pl": "piękna",
		  "zh-cn": "博福特"
		},
		"winddirection": {
			"en": "winddirection",
			"de": "Windrichtung",
			"ru": "направление ветра",
			"pt": "Direção do vento",
			"nl": "windrichting",
			"fr": "direction du vent",
			"it": "la direzione del vento",
			"es": "dirección del viento",
			"pl": "kierunek wiatru",
			"zh-cn": "风向"
		},
		"degree": {
		  "en": "degree",
		  "de": "Grad",
		  "ru": "степень",
		  "pt": "grau",
		  "nl": "rang",
		  "fr": "degré",
		  "it": "livello",
		  "es": "la licenciatura",
		  "pl": "stopień",
		  "zh-cn": "程度"
		},
		"2 direction characters": {
		  "en": "2 direction characters",
		  "de": "2 Richtungszeichen",
		  "ru": "2 символа направления",
		  "pt": "2 caracteres de direção",
		  "nl": "2 richting karakters",
		  "fr": "2 personnages de direction",
		  "it": "2 caratteri di direzione",
		  "es": "2 caracteres de dirección",
		  "pl": "2 znaki kierunkowe",
		  "zh-cn": "2个方向字符"
		},
		"3 direction characters": {
		  "en": "3 direction characters",
		  "de": "3 Richtungszeichen",
		  "ru": "3 символа направления",
		  "pt": "3 caracteres de direção",
		  "nl": "3 richting karakters",
		  "fr": "3 personnages de direction",
		  "it": "3 caratteri di direzione",
		  "es": "3 caracteres de dirección",
		  "pl": "3 znaki kierunkowe",
		  "zh-cn": "3个方向字符"
		},
		"precipitationamount": {
			"en": "precipitationamount",
			"de": "Niederschlagsmenge",
			"ru": "количество осадков",
			"pt": "quantidade de precipitação",
			"nl": "neerslaghoeveelheid",
			"fr": "quantité de précipitations",
			"it": "quantità di precipitazioni",
			"es": "cantidad de precipitación",
			"pl": "ilość opadów",
			"zh-cn": "降水量"
		},
		"mm": {
		  "en": "mm",
		  "de": "mm",
		  "ru": "мм",
		  "pt": "milímetros",
		  "nl": "mm",
		  "fr": "mm",
		  "it": "mm",
		  "es": "mm",
		  "pl": "mm",
		  "zh-cn": "毫米"
		},
		"inch": {
		  "en": "inch",
		  "de": "Zoll",
		  "ru": "дюйм",
		  "pt": "polegada",
		  "nl": "inch",
		  "fr": "pouce",
		  "it": "pollice",
		  "es": "pulgada",
		  "pl": "cal",
		  "zh-cn": "英寸"
		},
		"timeformat": {
			"en": "timeformat",
			"de": "Zeitformat",
			"ru": "формат времени",
			"pt": "formato de tempo",
			"nl": "Tijd formaat",
			"fr": "format de l'heure",
			"it": "formato orario",
			"es": "formato de tiempo",
			"pl": "format czasu",
			"zh-cn": "时间格式"
		},
		"Y-M-D": {
		  "en": "Y-M-D",
		  "de": "Y-M-D",
		  "ru": "Г-М-Д",
		  "pt": "Y-M-D",
		  "nl": "J-M-D",
		  "fr": "A-M-D",
		  "it": "Y-M-D",
		  "es": "Y-M-D",
		  "pl": "Y-M-D",
		  "zh-cn": "年-月-日"
		},
		"YMD": {
		  "en": "YMD",
		  "de": "YMD",
		  "ru": "YMD",
		  "pt": "YMD",
		  "nl": "YMD",
		  "fr": "AMJ",
		  "it": "YMD",
		  "es": "YMD",
		  "pl": "YMD",
		  "zh-cn": "长城"
		},
		"iso8601": {
		  "en": "iso8601",
		  "de": "iso8601",
		  "ru": "iso8601",
		  "pt": "iso8601",
		  "nl": "iso8601",
		  "fr": "iso8601",
		  "it": "iso8601",
		  "es": "iso8601",
		  "pl": "iso8601",
		  "zh-cn": "iso8601"
		},
		"timestamp_utc": {
			"en": "timestamp (UTC)",
			"de": "Zeitstempel (UTC)",
			"ru": "отметка времени (UTC)",
			"pt": "carimbo de data / hora (UTC)",
			"nl": "tijdstempel (UTC)",
			"fr": "horodatage (UTC)",
			"it": "timestamp (UTC)",
			"es": "marca de tiempo (UTC)",
			"pl": "znacznik czasu (UTC)",
			"zh-cn": "时间戳 (UTC)"
		},
		"timestamp_ms_utc": {
			"en": "timestamp (MS_UTC)",
			"de": "Zeitstempel (MS_UTC)",
			"ru": "отметка времени (MS_UTC)",
			"pt": "carimbo de data / hora (MS_UTC)",
			"nl": "tijdstempel (MS_UTC)",
			"fr": "horodatage (MS_UTC)",
			"it": "timestamp (MS_UTC)",
			"es": "marca de tiempo (MS_UTC)",
			"pl": "sygnatura czasowa (MS_UTC)",
			"zh-cn": "时间戳 (MS_UTC)"
		},
		"api_explanation": {
			"en": "For non-commercial uses, meteoblue.com offers the meteogram 5 days and the data package basic-day. Non-commercial uses are all uses without direct profit purposes. Get meteoblue non-commercial API service <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">here</a>. A description of the values can be found <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">here</a>.",
			"de": "Für nicht-kommerzielle Zwecke bietet meteoblue.com das Meteogramm 5 Tage und das Datenpaket Basic-Day an. Nicht-kommerzielle Nutzungen sind alle Nutzungen ohne unmittelbaren Gewinnzweck. Erhalten Sie meteoblue nicht-kommerziellen API - Service <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">hier</a> . Eine Beschreibung der Werte finden Sie <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">hier</a> .",
			"ru": "Для некоммерческого использования meteoblue.com предлагает метеограмму за 5 дней и пакет данных «базовый день». Некоммерческое использование - это все виды использования без прямой прибыли. Получите некоммерческий API-сервис meteoblue <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">здесь</a> . Описание значений можно найти <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">здесь</a> .",
			"pt": "Para usos não comerciais, meteoblue.com oferece o meteograma 5 dias e o pacote de dados básico-dia. Usos não comerciais são todos os usos sem fins lucrativos diretos. Obtenha o serviço API não comercial de meteoblue <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">aqui</a> . Uma descrição dos valores pode ser encontrada <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">aqui</a> .",
			"nl": "Voor niet-commercieel gebruik biedt meteoblue.com het meteogram 5 dagen en het datapakket basisdag aan. Niet-commercieel gebruik is elk gebruik zonder directe winstoogmerk. Get meteoblue niet-commercieel API <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">hier</a> . Een beschrijving van de waarden vindt u <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">hier</a> .",
			"fr": "Pour des usages non commerciaux, meteoblue.com propose le météogramme 5 jours et le forfait data base-jour. Les utilisations non commerciales sont toutes des utilisations sans but lucratif direct. Obtenez le service API non commercial de meteoblue <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">ici</a> . Une description des valeurs peut être trouvée <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">ici</a> .",
			"it": "Per usi non commerciali, meteoblue.com offre il meteogramma 5 giorni e il pacchetto dati basic-day. Gli usi non commerciali sono tutti gli usi senza fini di lucro diretto. Ottieni il servizio API non commerciale di meteoblue <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">qui</a> . Una descrizione dei valori può essere trovata <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">qui</a> .",
			"es": "Para usos no comerciales, meteoblue.com ofrece el meteograma 5 días y el paquete de datos basic-day. Los usos no comerciales son todos los usos sin fines de lucro directo. Obtenga el servicio API no comercial de meteoblue <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">aquí</a> . Puede encontrar una descripción de los valores <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">aquí</a> .",
			"pl": "Do zastosowań niekomercyjnych meteoblue.com oferuje meteogram 5 dni i pakiet danych basic-day. Zastosowania niekomercyjne to wszystkie zastosowania bez bezpośredniego zysku. Skorzystaj z niekomercyjnej usługi API meteoblue <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">tutaj</a> . Opis wartości można znaleźć <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">tutaj</a> .",
			"zh-cn": "对于非商业用途，meteoblue.com 提供 5 天的气象图和基本天的数据包。非商业用途是所有没有直接盈利目的的用途。 <a href=\"https://content.meteoblue.com/en/access-options/meteoblue-weather-api/non-commercial-use\" target=\"_blank\">在此处</a>获取meteoblue 非商业API 服务。<a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction\" target=\"_blank\">可以在此处</a>找到这些值的说明。"
		}, 
		"required": {
			"en": "required",
			"de": "erforderlich",
			"ru": "требуется",
			"pt": "obrigatório",
			"nl": "verplicht",
			"fr": "obligatoire",
			"it": "necessario",
			"es": "requerido",
			"pl": "wymagany",
			"zh-cn": "必需的"
		  }
};