/*global systemDictionary:true */
'use strict';

systemDictionary = {
		"API connection settings": {
		  "en": "API connection settings",
		  "de": "API-Verbindungseinstellungen",
		  "ru": "Настройки подключения API",
		  "pt": "Configurações de conexão API",
		  "nl": "Instellingen voor API-verbinding",
		  "fr": "Paramètres de connexion API",
		  "it": "Impostazioni di connessione API",
		  "es": "Configuración de conexión API",
		  "pl": "Ustawienia połączenia API",
		  "zh-cn": "API 连接设置"
		},
		"location": {
		  "en": "location",
		  "de": "Lage",
		  "ru": "место нахождения",
		  "pt": "localização",
		  "nl": "plaats",
		  "fr": "emplacement",
		  "it": "Posizione",
		  "es": "localización",
		  "pl": "Lokalizacja",
		  "zh-cn": "地点"
		},
		"latitude": {
			"en": "latitude (default: system configuration)",
			"de": "Breitengrad (Standard: Systemkonfiguration)",
			"ru": "широта (по умолчанию: конфигурация системы)",
			"pt": "latitude (padrão: configuração do sistema)",
			"nl": "breedtegraad (standaard: systeemconfiguratie)",
			"fr": "latitude (par défaut : configuration du système)",
			"it": "latitudine (predefinito: configurazione del sistema)",
			"es": "latitud (predeterminado: configuración del sistema)",
			"pl": "szerokość geograficzna (domyślnie: konfiguracja systemu)",
			"zh-cn": "纬度（默认：系统配置）"
		},
		"longitude": {
			"en": "longitude (default: system configuration)",
			"de": "Längengrad (Standard: Systemkonfiguration)",
			"ru": "долгота (по умолчанию: конфигурация системы)",
			"pt": "longitude (padrão: configuração do sistema)",
			"nl": "lengtegraad (standaard: systeemconfiguratie)",
			"fr": "longitude (par défaut : configuration du système)",
			"it": "longitudine (predefinito: configurazione del sistema)",
			"es": "longitud (predeterminado: configuración del sistema)",
			"pl": "długość geograficzna (domyślnie: konfiguracja systemu)",
			"zh-cn": "经度（默认：系统配置）"
		},
		"elevation": {
			"en": "elevation (default: automatic detection)",
			"de": "Höhe (Standard: automatische Erkennung)",
			"ru": "высота (по умолчанию: автоматическое определение)",
			"pt": "elevação (padrão: detecção automática)",
			"nl": "hoogte (standaard: automatische detectie)",
			"fr": "altitude (par défaut : détection automatique)",
			"it": "elevazione (impostazione predefinita: rilevamento automatico)",
			"es": "elevación (predeterminado: detección automática)",
			"pl": "elewacja (domyślnie: automatyczne wykrywanie)",
			"zh-cn": "海拔（默认：自动检测）"
		},
		"timezone": {
			"en": "timezone (default: automatic detection)",
			"de": "Zeitzone (Standard: automatische Erkennung)",
			"ru": "часовой пояс (по умолчанию: автоматическое определение)",
			"pt": "fuso horário (padrão: detecção automática)",
			"nl": "tijdzone (standaard: automatische detectie)",
			"fr": "fuseau horaire (par défaut : détection automatique)",
			"it": "fuso orario (predefinito: rilevamento automatico)",
			"es": "zona horaria (predeterminado: detección automática)",
			"pl": "strefa czasowa (domyślnie: automatyczne wykrywanie)",
			"zh-cn": "时区（默认：自动检测）"
		},
		"Europe/Zurich": {
		  "en": "Europe/Zurich",
		  "de": "Europa/Zürich",
		  "ru": "Европа/Цюрих",
		  "pt": "Europa/Zurique",
		  "nl": "Europa/Zürich",
		  "fr": "Europe/Zurich",
		  "it": "Europa/Zurigo",
		  "es": "Europa/Zúrich",
		  "pl": "Europa/Zurych",
		  "zh-cn": "欧洲/苏黎世"
		},
		"Europe/Berlin": {
		  "en": "Europe/Berlin",
		  "de": "Europa/Berlin",
		  "ru": "Европа/Берлин",
		  "pt": "Europa/Berlim",
		  "nl": "Europa/Berlijn",
		  "fr": "Europe/Berlin",
		  "it": "Europa/Berlino",
		  "es": "Europa/Berlín",
		  "pl": "Europa/Berlin",
		  "zh-cn": "欧洲/柏林"
		},
		"apikey": {
			"en": "API-Key (required)",
			"de": "API-Schlüssel (erforderlich)",
			"ru": "API-ключ (обязательно)",
			"pt": "API-Key (obrigatório)",
			"nl": "API-sleutel (verplicht)",
			"fr": "Clé API (obligatoire)",
			"it": "Chiave API (richiesto)",
			"es": "API-Key (requerido)",
			"pl": "Klucz API (wymagany)",
			"zh-cn": "API-Key（必填）"
		},
		"temperature": {
			"en": "temperature (default: celsius)",
			"de": "Temperatur (Standard: Celsius)",
			"ru": "температура (по умолчанию: Цельсия)",
			"pt": "temperatura (padrão: celsius)",
			"nl": "temperatuur (standaard: Celsius)",
			"fr": "température (par défaut : Celsius)",
			"it": "temperatura (predefinito: Celsius)",
			"es": "temperatura (por defecto: celsius)",
			"pl": "temperatura (domyślnie: stopnie Celsjusza)",
			"zh-cn": "温度（默认：摄氏度）"
		},
		"celsius": {
		  "en": "celsius",
		  "de": "Celsius",
		  "ru": "по Цельсию",
		  "pt": "Celsius",
		  "nl": "Celsius",
		  "fr": "celsius",
		  "it": "centigrado",
		  "es": "Celsius",
		  "pl": "Celsjusz",
		  "zh-cn": "摄氏"
		},
		"farenheit": {
		  "en": "farenheit",
		  "de": "Fahrenheit",
		  "ru": "Фаренгейт",
		  "pt": "farenheit",
		  "nl": "farenheit",
		  "fr": "farenheit",
		  "it": "farenheit",
		  "es": "farenheit",
		  "pl": "Farenheita",
		  "zh-cn": "华氏度"
		},
		"windspeed": {
			"en": "windspeed (default: kilometers per hour)",
			"de": "Windgeschwindigkeit (Standard: Kilometer pro Stunde)",
			"ru": "скорость ветра (по умолчанию: километров в час)",
			"pt": "velocidade do vento (padrão: quilômetros por hora)",
			"nl": "windsnelheid (standaard: kilometer per uur)",
			"fr": "vitesse du vent (par défaut : kilomètres par heure)",
			"it": "velocità del vento (predefinito: chilometri all'ora)",
			"es": "velocidad del viento (predeterminado: kilómetros por hora)",
			"pl": "prędkość wiatru (domyślnie: kilometry na godzinę)",
			"zh-cn": "风速（默认：公里每小时）"
		},
		"kilometer per hour": {
		  "en": "kilometer per hour",
		  "de": "Kilometer pro Stunde",
		  "ru": "километр в час",
		  "pt": "quilometro por hora",
		  "nl": "kilometer per uur",
		  "fr": "kilomètre par heure",
		  "it": "chilometro all'ora",
		  "es": "kilómetro por hora",
		  "pl": "kilometr na godzinę",
		  "zh-cn": "每小时公里"
		},
		"meter per second": {
		  "en": "meter per second",
		  "de": "Meter pro Sekunde",
		  "ru": "метр в секунду",
		  "pt": "metro por segundo",
		  "nl": "meter per seconde",
		  "fr": "mètre par seconde",
		  "it": "metro al secondo",
		  "es": "metro por segundo",
		  "pl": "metr na sekundę",
		  "zh-cn": "米每秒"
		},
		"miles per hour": {
		  "en": "miles per hour",
		  "de": "Meilen pro Stunde",
		  "ru": "миль в час",
		  "pt": "milhas por hora",
		  "nl": "mijl per uur",
		  "fr": "miles par heure",
		  "it": "miglia all'ora",
		  "es": "millas por hora",
		  "pl": "mile na godzinę",
		  "zh-cn": "英里每小时"
		},
		"knots": {
		  "en": "knots",
		  "de": "Knoten",
		  "ru": "узлы",
		  "pt": "nós",
		  "nl": "knopen",
		  "fr": "nœuds",
		  "it": "nodi",
		  "es": "nudos",
		  "pl": "węzły",
		  "zh-cn": "结"
		},
		"beaufort": {
		  "en": "beaufort",
		  "de": "beauffort",
		  "ru": "Бофорт",
		  "pt": "Beaufort",
		  "nl": "schoonheid",
		  "fr": "beaufort",
		  "it": "bello",
		  "es": "Beaufort",
		  "pl": "piękna",
		  "zh-cn": "博福特"
		},
		"winddirection": {
			"en": "winddirection (default: degree)",
			"de": "Windrichtung (Standard: Grad)",
			"ru": "направление ветра (по умолчанию: градус)",
			"pt": "direção do vento (padrão: grau)",
			"nl": "windrichting (standaard: graad)",
			"fr": "direction du vent (par défaut : degré)",
			"it": "direzione del vento (predefinito: gradi)",
			"es": "dirección del viento (predeterminado: grado)",
			"pl": "kierunek wiatru (domyślnie: stopień)",
			"zh-cn": "风向（默认：度）"
		},
		"degree": {
		  "en": "degree",
		  "de": "Grad",
		  "ru": "степень",
		  "pt": "grau",
		  "nl": "rang",
		  "fr": "degré",
		  "it": "livello",
		  "es": "la licenciatura",
		  "pl": "stopień",
		  "zh-cn": "程度"
		},
		"2 direction characters": {
		  "en": "2 direction characters",
		  "de": "2 Richtungszeichen",
		  "ru": "2 символа направления",
		  "pt": "2 caracteres de direção",
		  "nl": "2 richting karakters",
		  "fr": "2 personnages de direction",
		  "it": "2 caratteri di direzione",
		  "es": "2 caracteres de dirección",
		  "pl": "2 znaki kierunkowe",
		  "zh-cn": "2个方向字符"
		},
		"3 direction characters": {
		  "en": "3 direction characters",
		  "de": "3 Richtungszeichen",
		  "ru": "3 символа направления",
		  "pt": "3 caracteres de direção",
		  "nl": "3 richting karakters",
		  "fr": "3 personnages de direction",
		  "it": "3 caratteri di direzione",
		  "es": "3 caracteres de dirección",
		  "pl": "3 znaki kierunkowe",
		  "zh-cn": "3个方向字符"
		},
		"precipitationamount": {
			"en": "precipitationamount (default: millimeter )",
			"de": "Niederschlagsmenge (Standard: Millimeter)",
			"ru": "сумма осадков (по умолчанию: миллиметры)",
			"pt": "quantidade de precipitação (padrão: milímetro)",
			"nl": "neerslaghoeveelheid (standaard: millimeter)",
			"fr": "montant de précipitation (par défaut : millimètre )",
			"it": "quantità di precipitazioni (predefinito: millimetro )",
			"es": "cantidad de precipitación (por defecto: milímetro)",
			"pl": "ilość opadów (domyślnie: milimetr )",
			"zh-cn": "降水量（默认值：毫米）"
		},
		"mm": {
		  "en": "mm",
		  "de": "mm",
		  "ru": "мм",
		  "pt": "milímetros",
		  "nl": "mm",
		  "fr": "mm",
		  "it": "mm",
		  "es": "mm",
		  "pl": "mm",
		  "zh-cn": "毫米"
		},
		"inch": {
		  "en": "inch",
		  "de": "Zoll",
		  "ru": "дюйм",
		  "pt": "polegada",
		  "nl": "inch",
		  "fr": "pouce",
		  "it": "pollice",
		  "es": "pulgada",
		  "pl": "cal",
		  "zh-cn": "英寸"
		},
		"timeformat": {
			"en": "timeformat (default: Year-Month-Day Hour:Minute)",
			"de": "Zeitformat (Standard: Jahr-Monat-Tag Stunde:Minute)",
			"ru": "формат времени (по умолчанию: год-месяц-день, час: минута)",
			"pt": "formato de hora (padrão: Ano-Mês-Dia Hora: Minuto)",
			"nl": "tijdnotatie (standaard: Jaar-Maand-Dag Uur:Minuut)",
			"fr": "timeformat (par défaut : Année-Mois-Jour Heure : Minute)",
			"it": "formatoora (predefinito: Anno-Mese-Giorno Ora:Minuti)",
			"es": "formato de hora (predeterminado: Año-Mes-Día Hora: Minuto)",
			"pl": "format czasu (domyślnie: rok-miesiąc-dzień godzina:minuta)",
			"zh-cn": "时间格式（默认：年-月-日小时：分钟）"
		},
		"Y-M-D": {
		  "en": "Y-M-D",
		  "de": "Y-M-D",
		  "ru": "Г-М-Д",
		  "pt": "Y-M-D",
		  "nl": "J-M-D",
		  "fr": "A-M-D",
		  "it": "Y-M-D",
		  "es": "Y-M-D",
		  "pl": "Y-M-D",
		  "zh-cn": "年-月-日"
		},
		"YMD": {
		  "en": "YMD",
		  "de": "YMD",
		  "ru": "YMD",
		  "pt": "YMD",
		  "nl": "YMD",
		  "fr": "AMJ",
		  "it": "YMD",
		  "es": "YMD",
		  "pl": "YMD",
		  "zh-cn": "长城"
		},
		"iso8601": {
		  "en": "iso8601",
		  "de": "iso8601",
		  "ru": "iso8601",
		  "pt": "iso8601",
		  "nl": "iso8601",
		  "fr": "iso8601",
		  "it": "iso8601",
		  "es": "iso8601",
		  "pl": "iso8601",
		  "zh-cn": "iso8601"
		},
		"timestamp_utc": {
			"en": "timestamp (UTC)",
			"de": "Zeitstempel (UTC)",
			"ru": "отметка времени (UTC)",
			"pt": "carimbo de data / hora (UTC)",
			"nl": "tijdstempel (UTC)",
			"fr": "horodatage (UTC)",
			"it": "timestamp (UTC)",
			"es": "marca de tiempo (UTC)",
			"pl": "znacznik czasu (UTC)",
			"zh-cn": "时间戳 (UTC)"
		},
		"timestamp_ms_utc": {
			"en": "timestamp (MS_UTC)",
			"de": "Zeitstempel (MS_UTC)",
			"ru": "отметка времени (MS_UTC)",
			"pt": "carimbo de data / hora (MS_UTC)",
			"nl": "tijdstempel (MS_UTC)",
			"fr": "horodatage (MS_UTC)",
			"it": "timestamp (MS_UTC)",
			"es": "marca de tiempo (MS_UTC)",
			"pl": "sygnatura czasowa (MS_UTC)",
			"zh-cn": "时间戳 (MS_UTC)"
		},
		"api_explanation": {
			"en": "more information can be found <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">here</a>",
			"de": "weitere Informationen finden Sie <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">hier</a>",
			"ru": "дополнительную информацию можно найти <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">здесь</a>",
			"pt": "mais informações podem ser encontradas <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">aqui</a>",
			"nl": "meer informatie vind je <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">hier</a>",
			"fr": "plus d'informations peuvent être trouvées <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">ici</a>",
			"it": "maggiori informazioni possono essere trovate <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">qui</a>",
			"es": "se puede encontrar más información <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">aquí</a>",
			"pl": "więcej informacji znajdziesz <a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">tutaj</a>",
			"zh-cn": "更多信息可以在<a href=\"https://docs.meteoblue.com/en/weather-apis/packages-api/introduction#time-zone\" target=\"_blank\">这里找到</a>"
		}, 
		"required": {
			"en": "required",
			"de": "erforderlich",
			"ru": "требуется",
			"pt": "obrigatório",
			"nl": "verplicht",
			"fr": "obligatoire",
			"it": "necessario",
			"es": "requerido",
			"pl": "wymagany",
			"zh-cn": "必需的"
		  }
};